# Generated by Django 5.0.3 on 2025-07-04 06:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('duration', models.DurationField()),
                ('release_date', models.DateTimeField()),
                ('file_url', models.FileField(upload_to='songs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3'])])),
                ('cover_image', models.ImageField(upload_to='songs_img/')),
                ('lyrics', models.TextField()),
                ('language', models.CharField(max_length=20)),
                ('views', models.PositiveBigIntegerField()),
                ('likes_count', models.PositiveBigIntegerField()),
            ],
        ),
    ]
