# Generated by Django 5.0.3 on 2025-07-04 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='songs',
            old_name='file_url',
            new_name='songs',
        ),
    ]
