# Generated by Django 5.0.3 on 2025-07-04 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_rename_file_url_songs_songs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songs',
            name='duration',
        ),
    ]
