# Generated by Django 5.0.3 on 2025-07-04 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_remove_songs_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
