# Generated by Django 5.0.3 on 2025-07-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0005_aritist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='aritist',
            name='songs',
        ),
        migrations.AddField(
            model_name='songs',
            name='artists',
            field=models.ManyToManyField(related_name='artist', to='songs.aritist'),
        ),
        migrations.AlterField(
            model_name='aritist',
            name='artist_bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='aritist',
            name='artist_image',
            field=models.FileField(blank=True, upload_to='artist_img/'),
        ),
        migrations.AlterField(
            model_name='aritist',
            name='country',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='songs',
            name='likes_count',
            field=models.PositiveBigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='songs',
            name='lyrics',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='songs',
            name='release_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='songs',
            name='views',
            field=models.PositiveBigIntegerField(blank=True),
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('cover_image', models.FileField(upload_to='album_image/')),
                ('description', models.TextField(blank=True)),
                ('artist', models.ManyToManyField(related_name='album_aritist', to='songs.aritist')),
                ('songs', models.ManyToManyField(related_name='album_songs', to='songs.songs')),
            ],
        ),
    ]
