# Generated by Django 5.0.3 on 2025-07-05 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Accounts', '0009_rename_display_name_userprofile_user_name_and_more'),
        ('songs', '0008_alter_playlist_created_at_alter_playlist_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histroy_song', to='songs.songs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_user', to='User_Accounts.userprofile')),
            ],
            options={
                'ordering': ['-played_at'],
            },
        ),
    ]
