# Generated by Django 5.0.3 on 2025-07-05 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Accounts', '0009_rename_display_name_userprofile_user_name_and_more'),
        ('songs', '0009_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_at', models.DateTimeField(auto_now_add=True)),
                ('duration_played', models.DurationField()),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playback_user', to='songs.songs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playback_user', to='User_Accounts.userprofile')),
            ],
        ),
    ]
