# Generated by Django 5.0.3 on 2025-07-07 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0011_queue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='position',
            field=models.IntegerField(blank=True),
        ),
    ]
