# Generated by Django 5.0.3 on 2025-07-07 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0012_alter_queue_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
