# Generated by Django 5.0.3 on 2025-07-07 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0014_genre_alter_songs_artists_songs_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='release_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
