# Generated by Django 5.0.3 on 2025-07-07 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0015_alter_songs_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='likes_count',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='songs',
            name='views',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
