# Generated by Django 5.0.3 on 2025-07-07 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Accounts', '0009_rename_display_name_userprofile_user_name_and_more'),
        ('songs', '0016_alter_songs_likes_count_alter_songs_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_at', models.DateTimeField(auto_now_add=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_song', to='songs.songs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_user', to='User_Accounts.userprofile')),
            ],
        ),
    ]
