# Generated by Django 5.0.3 on 2025-07-08 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_Accounts', '0009_rename_display_name_userprofile_user_name_and_more'),
        ('songs', '0017_like'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'song')},
        ),
        migrations.AlterUniqueTogether(
            name='queue',
            unique_together={('user', 'song')},
        ),
    ]
