# Generated by Django 5.0.3 on 2025-07-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0019_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
