# Generated by Django 5.0.3 on 2025-07-13 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0021_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='artist',
        ),
    ]
