# Generated by Django 5.0.3 on 2025-07-16 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Accounts', '0011_remove_userprofile_liked_songs'),
        ('songs', '0022_remove_album_artist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block_songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocked_time', models.DateTimeField(auto_now_add=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_songs_song', to='songs.songs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_song_user', to='User_Accounts.userprofile')),
            ],
            options={
                'unique_together': {('user', 'song')},
            },
        ),
    ]
