# Generated by Django 5.0.3 on 2025-07-17 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Accounts', '0011_remove_userprofile_liked_songs'),
        ('songs', '0023_block_songs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song_play',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_at', models.DateTimeField(auto_now_add=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_play_song', to='songs.songs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_play_user', to='User_Accounts.userprofile')),
            ],
        ),
    ]
