# Generated by Django 5.0.3 on 2025-07-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0024_song_play'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='views',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
    ]
