# Generated by Django 5.0.3 on 2025-07-17 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_Accounts', '0011_remove_userprofile_liked_songs'),
        ('songs', '0025_alter_songs_views'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='song_play',
            unique_together={('user', 'song')},
        ),
    ]
