# Generated by Django 5.0.3 on 2025-07-04 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Accounts', '0003_alter_userprofile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.BigIntegerField(blank=True, max_length=10, null=True),
        ),
    ]
