# Generated by Django 5.0.3 on 2025-07-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Accounts', '0007_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo_url',
            field=models.ImageField(blank=True, null=True, upload_to='user_photo/'),
        ),
    ]
