# Generated by Django 5.0.3 on 2025-07-04 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_Accounts', '0008_alter_userprofile_photo_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='display_name',
            new_name='user_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
    ]
