# Generated by Django 5.0.3 on 2025-07-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Accounts', '0009_rename_display_name_userprofile_user_name_and_more'),
        ('songs', '0020_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='liked_songs',
            field=models.ManyToManyField(related_name='user_songs', to='songs.songs'),
        ),
    ]
