# Generated by Django 5.0.3 on 2025-07-13 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_Accounts', '0010_userprofile_liked_songs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='liked_songs',
        ),
    ]
